pmanager/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
    Route::resource('companies','CompaniesController');
    Route::get('projects/create/{company_id?}','ProjectsController@create');
    Route::post('projects/adduser','ProjectsController@adduser')->name('projects.adduser');
    Route::resource('projects','ProjectsController');
    Route::resource('roles','RolesController');
    Route::resource('tasks','TasksController');
    Route::resource('users','UsersController');
    Route::resource('comments','CommentsController');
});

pmanager/app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = [
        'name',
        'description',
        'company_id',
        'user_id',
        'days',
    ];

    public function users(){
        return $this->belongsToMany('App\User');
    }
    
    public function company(){
        return $this->belongsTo('App\Company');
    }

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}

pmanager/app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use App\Company;
use App\User;
use App\ProjectUser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if(Auth::check()){
            $projects = Project::where('user_id', Auth::user()->id)->get();

            return view('projects.index', ['projects' => $projects]);
        }
        return view('auth.login');
    }

    public function adduser(Request $request)
    {
        //
        $project = Project::find($request->input('project_id'));
        $user = User::where('email', $request->input('email'))->first();
        $projectUser = ProjectUser::where('user_id',$user->id)
                                    ->where('project_id',$project->id)
                                    ->first();
        if($projectUser){
            return redirect()->route('projects.show', ['project'=>$project->id])
            ->with('success', $request->input('email').' is already a member of this project');
        }
        if(Auth::user()->id == $project->user_id){
            if($user && $project){
                $project->users()->toggle($user->id);
                return redirect()->route('projects.show', ['project'=>$project->id])
                ->with('success', $request->input('email').' was added to project');
            }
        }
        
        return redirect()->route('projects.show', ['project'=>$project->id])
        ->with('success', ' error adding user to project');
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($company_id = null)
    {
        //
        $companies = null;
        if(!$company_id){
            $companies = Company::where('user_id', Auth::user()->id)->get();
        }
        return view('projects.create',["company_id"=>$company_id, "companies" => $companies]);   
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if(Auth::check()){
            $project = Project::create([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
                'company_id' => $request->input('company_id'),
                'user_id' => Auth::user()->id
            ]);
            if($project){
                return redirect()->route('projects.show', ['Project'=> $project->id])
                ->with('success', 'Project created');
            }
        }
        return back()->withInput()->with('error', 'Project could not be created');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        //
        //$project = Project::where('id', $project->id)->first();
        $project = Project::find($project->id);
        $comments = $project->comments;
        return view('projects.show', ['project' => $project, 'comments' => $comments]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        //
        $project = Project::find($project->id);
        return view('projects.edit', ['Project' => $project]);   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        //
        $projectUpdate = Project::where('id', $project->id)
                                ->update([
                                    'name'=>$request->input('name'),
                                    'description'=>$request->input('description')
                                ]);
        if($projectUpdate){
            return redirect()->route('projects.show',['Project'=>$project->id])
            ->with('success', 'Project updated');
        }
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
        $findProject = Project::find($project->id);
        if($findProject->delete()){
            return redirect()->route('projects.index')
            ->with('success', 'Project deleted');
        }
        return back()->withInput()->with('error', 'Project could not be deleted');
    }
}

pmanager/resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')


  <!-- Main jumbotron for a primary marketing message or call to action -->
<div class="col-sm-9 col-md-9 col-lg-9 pull-left">
    <div class="row col-md-12 col-lg-12 col-sm-12" style="background:white; margin:10px">
        <form method="post" action="{{ route('projects.store')}}">
        {{ csrf_field() }}
        <div class="form-group">
            <label for="project-name">Name <span class="required">*</span> </label>
            <input placeholder="Enter name"
                   id="project-name"
                   required
                   name="name"
                   spellcheck="false"
                   class="form-control"
                   />
        </div>
        @if($companies != null)
            <div class="form-group">
                <label for="company-content">Select company <span class="required">*</span> </label>
                <select name="company_id" class="form-control">
                    @foreach($companies as $company)
                    <option value="{{ $company->id}}">{{ $company->name }}</option>
                    @endforeach
                </select>
            </div>
        @else
            <input type="hidden" name="company_id" value="{{ $company_id }}">
        @endif
        <div class="form-group">
            <label for="project-description">Description <span class="required">*</span> </label>
            <textarea placeholder="Enter description"
                   style="resize: vertical"
                   id="project-content"
                   name="description"
                   rows="5" spellcheck="false"
                   class="form-control autosize-target text-left"
                   ></textarea>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Submit"/>
        </div>
        </form>
    </div>
</div>
<div class="col-sm-3 col-md-3 col-lg-3 pull-right">
    <div class="p-3">
        <h4 class="font-italic">Actions</h4>
        <ol class="list-unstyled">
          <li><a href="/projects">My projects</a></li>
        </ol>
    </div>
</div>


@endsection

pmanager/resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')


  <!-- Main jumbotron for a primary marketing message or call to action -->
<div class="col-sm-9 col-md-9 col-lg-9 pull-left">
    <div class="row col-md-12 col-lg-12 col-sm-12" style="background:white; margin:10px">
        <form method="post" action="{{ route('companies.update',[$company->id])}}">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="put">
        <div class="form-group">
            <label for="company-name">Name <span class="required">*</span> </label>
            <input placeholder="Enter name"
                   id="company-name"
                   required
                   name="name"
                   spellcheck="false"
                   class="form-control"
                   value="{{ $company->name }}"
                   />
        </div>
        <div class="form-group">
            <label for="company-description">Description <span class="required">*</span> </label>
            <textarea placeholder="Enter description"
                   style="resize: vertical"
                   id="company-content"
                   name="description"
                   rows="5" spellcheck="false"
                   class="form-control autosize-target text-left"
                   >{{ $company->description }}</textarea>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Submit"/>
        </div>
        </form>
    </div>
</div>
<div class="col-sm-3 col-md-3 col-lg-3 pull-right">
    <div class="p-3">
        <h4 class="font-italic">Actions</h4>
        <ol class="list-unstyled">
          <li><a href="/companies/{{ $company->id }}/edit">Edit</a></li>
          <li><a href="/companies/delete/{{ $company->id }}">Delete</a></li>
          <li><a href="/companies/add">Add new member</a></li>
        </ol>
    </div>
</div>


@endsection

pmanager/resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-6 col-lg-6 col-md-offset-2  col-lg-offset-3">
    <div class="panel panel-primary">
    <div class="panel-heading"><a class="pull-right btn btn-primary btn-sm" href="/projects/create">Create new project</a></div>
    <div class="panel-body">
    
    <ul class="list-group">
    <li class="list-group-item active">Projects</li>
        @foreach($projects as $project)
            <li class="list-group-item"><a href="/companies/{{ $project->id }}">{{ $project->name }}</a></li>
        @endforeach
    </ul>
    </div>
    </div>
</div>
    
@endsection

pmanager/resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')


  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="col-sm-9 col-md-9 col-lg-9 pull-left">
  <div class="well well-lg">
      <h1>{{ $project->name }}</h1>
      <p>{{ $project->description }}</p>
      <!--<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p> -->
  </div>
    <!-- Example row of columns -->
    <div class="row" style="background:white; margin:10px">
    <a href="/projects/create" class="pull-right btn btn-primary btn-sm">Add project</a>
    
    
   <br/> 
   @include('partials.comments')
  <div class="row container-fluid">
    <form method="post" action="{{ route('comments.store')}}">
        {{ csrf_field() }}
        <input type="hidden" name="commentable_type" value="App\Project">
        <input type="hidden" name="commentable_id" value="{{ $project->id}}">
        <div class="form-group">
            <label for="comment-description">Comment <span class="required">*</span> </label>
            <textarea placeholder="Enter comment"
                   style="resize: vertical"
                   id="comment-content"
                   name="body"
                   rows="5" spellcheck="false"
                   class="form-control autosize-target text-left"
                   ></textarea>
        </div>
        <div class="form-group">
            <label for="comment-description">Proof of work done (Url/Photos) <span class="required">*</span> </label>
            <textarea placeholder="Enter url or screenshots"
                   style="resize: vertical"
                   id="comment-content"
                   name="url"
                   rows="3" spellcheck="false"
                   class="form-control autosize-target text-left"
                   ></textarea>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Submit"/>
        </div>
        </form>
      </div>
    
    
     </div>
    
</div>
    <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
       <div class="p-3">
        <h4 class="font-italic">Actions</h4>
        <ol class="list-unstyled">
          <li><a href="/projects/create">Add project</a></li>
          <li><a href="/projects">My projects</a></li>
          @if($project->user_id == Auth::user()->id)
            <li><a href="/projects/{{ $project->id }}/edit">Edit</a></li>
              <li>
                <a 
                href="#"
                  onclick="
                    var result = confirm('Хотите удалить?');
                      if(result){
                        event.preventDefault();
                        document.getElementById('logout-form').submit();
                      }
                  "
                >Delete</a>
                <form method="post" id="logout-form" action="{{ route('projects.destroy',[$project->id])}}" style="display:none;">
                      <input type="hidden" name="_method" value="delete">
                      {{ csrf_field() }}
              </form>
            </li>
          @endif
        </ol>
        <hr>
        <div class="p-3">
          <h4 class="font-italic">Add members</h4>
          <form method="post" action="{{ route('projects.adduser')}}">
            <div class="input-group">
              <input type="hidden" name="project_id" value="{{ $project->id }}">
              <input type="text" name="email" class="form-control" placeholder="Email">
              <span class="input-group-btn">
                <button type="submit" class="btn btn-primary">Add!</button>
              </span>
            </div>
            {{ csrf_field() }}
          </form>
        </div>
        <div class="p-3">
          <h4 class="font-italic">Team members</h4>
          <ol class="list-unstyled">
              @foreach($project->users as $user)
                  <li><a href="#">{{ $user->name }}</a></li>
              @endforeach
          </ol>
        </div>
      </div>
    </div>

  </div> <!-- /container -->


@endsection